### ISSUE TITLE
Enabling IPv6

### ISSUE THREAD

**Issue by olsio** [scaleway-community/scaleway-openvpn#23]
Now that Scaleway offers IPv6 it would be nice to adapt the openvpn configuration to also enable IPv6 endpoint and dual stack traffic routing.

**Comment by meyskens** [comment]
I was looking into this. Since only a single IP is offered an IPv6 NAT translation will be needed on the machine. Looking into this but as it is not exactly good practice (unless Scaleway will offer a more IPv6 soon) it is hard to find any documentation on this. I have set this up on an OpenWRT router might port the work i did there.

**Comment by multun** [comment]
implemented by 22c5aaf
